### ISSUE TITLE
startswith function

### ISSUE THREAD

**Issue by AleRob90** [Cludch/GTA-MP-webClient#1]
Hello in index.html on line 68 you need to change startswith function with startsWith. I can't do a pull request right now. To me that line is broke. Have a nice day

**Comment by Cludch** [comment]
Thanks, fixed it - https://github.com/Cludch/GTA-MP-webClient/commit/d255e9f5a3ba4daf1d7e84fe12ebcaaad496f52f
This part needs a rewrite nevertheless to check the name.
